### ISSUE TITLE
Helper for getting additional info by cop

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#107]
**Is your feature request related to a problem? Please describe.**

When we generate rubocop, for many offences it just disables some metrics (and this is a nice solution this time). 

```yml
# Offense count: 9689
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Enabled: false
```

But when we start to fix this cop, this is important for us:

1) Disable only files with offenses but check that rule for all other files.
2) Will be nice to see a number of offenses for each file (for making a better splitter PRs)  
3) Order files alphabetically

For those cases, I use the next script 

https://gist.github.com/roman-dubrovsky/a9f4b6e0481510673b0181885be3c76e#file-helper-rb

And after enabling the rule get the next result

```yml
~/Work/activedemand (master*) $ ruby test.rb
Style/HashSyntax:
  Exclude:
    - 'app/controllers/accounts_controller.rb' # 162
    - 'app/controllers/api/api_controller.rb' # 49
    - 'app/controllers/api/v1/campaigns_controller.rb' # 7
    - 'app/controllers/api/v1/contact_lists_controller.rb' # 6
    - 'app/controllers/api/v1/contacts_controller.rb' # 37
    - 'app/controllers/api/v1/cta_pages_controller.rb' # 11
    - 'app/controllers/api/v1/emails_controller.rb' # 9
    - 'app/controllers/api/v1/forms_controller.rb' # 8
    - 'app/controllers/api/v1/histories_controller.rb' # 31
    - 'app/controllers/api/v1/organizations_controller.rb' # 6
    - 'app/controllers/api/v1/phones_controller.rb' # 22
    - 'app/controllers/api/v1/smart_blocks_controller.rb' # 18
    - 'app/controllers/api/v1/web_hooks_controller.rb' # 15
    - 'app/controllers/application_controller.rb' # 242
    - 'app/controllers/appointment_schedulers_controller.rb' # 31
    - 'app/controllers/billing_controller.rb' # 100
    - 'app/controllers/builder_controller.rb' # 93
    - 'app/controllers/call_completion_automations_controller.rb' # 9
    - 'app/controllers/campaigns_controller.rb' # 145
    - 'app/controllers/concerns/campaign_findable.rb' # 3
    - 'app/controllers/confirmations_controller.rb' # 1
    - 'app/controllers/contact_lists_controller.rb' # 34
    - 'app/controllers/contact_segments_controller.rb' # 15
    - 'app/controllers/contacts_controller.rb' # 136
    - 'app/controllers/content_assets_controller.rb' # 18
    - 'app/controllers/content_blocks_controller.rb' # 70
    - 'app/controllers/content_images_controller.rb' # 24
    - 'app/controllers/content_menus_controller.rb' # 15
    - 'app/controllers/cta_pages_controller.rb' # 73
    - 'app/controllers/dashboards_controller.rb' # 3
    - 'app/controllers/dynamic_contents_controller.rb' # 57
    - 'app/controllers/dynamic_images_controller.rb' # 8
    - 'app/controllers/emails_controller.rb' # 87
    - 'app/controllers/forms_controller.rb' # 98
    - 'app/controllers/phones_controller.rb' # 63
    - 'app/controllers/portal_controller.rb' # 28
    - 'app/controllers/products_controller.rb' # 17
    - 'app/controllers/report_schedules_controller.rb' # 12
    - 'app/controllers/report_sections_controller.rb' # 33
    - 'app/controllers/reports_controller.rb' # 86
    - 'app/controllers/sessions_controller.rb' # 2
    - 'app/controllers/submit_controller.rb' # 128
    - 'app/controllers/users_controller.rb' # 29
    - 'app/controllers/utilities_controller.rb' # 249
    - 'app/controllers/workflows_controller.rb' # 94
    - 'app/models/account_stat.rb' # 15
    - 'app/models/affiliate_conversion.rb' # 1
    - 'app/models/animation.rb' # 1
    - 'app/models/appointment.rb' # 16
    - 'app/models/call_completion_automation.rb' # 3
    - 'app/models/call_route_scenario.rb' # 13
    - 'app/models/call_route_schedule.rb' # 2
    - 'app/models/call_route_schedule_day.rb' # 17
    - 'app/models/campaign.rb' # 230
    - 'app/models/campaign_goal.rb' # 121
    - 'app/models/contact.rb' # 146
    - 'app/models/contact_detail.rb' # 6
    - 'app/models/contact_history_click_stat.rb' # 25
    - 'app/models/contact_history_fact.rb' # 20
    - 'app/models/contact_history_form_stat.rb' # 30
    - 'app/models/contact_history_stat.rb' # 70
    - 'app/models/contact_history_summary_stat.rb' # 79
    - 'app/models/contact_list.rb' # 26
    - 'app/models/contact_relation.rb' # 4
    - 'app/models/contacts_workflow.rb' # 1
    - 'app/models/content_asset.rb' # 5
    - 'app/models/content_block.rb' # 193
    - 'app/models/content_blocks_email_template.rb' # 1
    - 'app/models/content_column.rb' # 20
    - 'app/models/content_column_item.rb' # 1
    - 'app/models/content_menu.rb' # 5
    - 'app/models/content_row.rb' # 37
    - 'app/models/cookie_accept.rb' # 1
    - 'app/models/crm_reference.rb' # 17
    - 'app/models/cta_page.rb' # 80
    - 'app/models/cta_page_split_test.rb' # 2
    - 'app/models/custom_field_type.rb' # 5
    - 'app/models/data_enrichment.rb' # 6
    - 'app/models/data_import_schedule.rb' # 4
    - 'app/models/dynamic_number_group.rb' # 6
    - 'app/models/email_broker_request.rb' # 2
    - 'app/models/email_error.rb' # 3
    - 'app/models/email_log.rb' # 1
    - 'app/models/email_log_reply.rb' # 1
    - 'app/models/email_template.rb' # 86
    - 'app/models/email_template_split_test.rb' # 10
    - 'app/models/form.rb' # 283
    - 'app/models/form_field.rb' # 3
    - 'app/models/forms_form_field.rb' # 42
    - 'app/models/goal_completion.rb' # 1
    - 'app/models/industry.rb' # 3
    - 'app/models/item_lead_score.rb' # 94
    - 'app/models/lead_notification.rb' # 34
    - 'app/models/linkedin_engagement.rb' # 2
    - 'app/models/list_category.rb' # 1
    - 'app/models/page_visit.rb' # 1
    - 'app/models/phone.rb' # 18
    - 'app/models/phone_purchase.rb' # 3
    - 'app/models/preview_image.rb' # 5
    - 'app/models/product.rb' # 3
    - 'app/models/query_filter.rb' # 1
    - 'app/models/report_schedule.rb' # 15
    - 'app/models/report_section.rb' # 62
    - 'app/models/report_section_series.rb' # 32
    - 'app/models/role.rb' # 2
    - 'app/models/social_media_account.rb' # 35
    - 'app/models/statistic_fact.rb' # 12
    - 'app/models/style_property.rb' # 101
    - 'app/models/subscription_price.rb' # 6
    - 'app/models/third_party_application.rb' # 52
    - 'app/models/transcript.rb' # 3
    - 'app/models/transcript_category.rb' # 2
    - 'app/models/twilio_forward.rb' # 16
    - 'app/models/workflow_action.rb' # 136
    - 'app/models/workflow_action_list.rb' # 2
    - 'app/models/workflow_check.rb' # 213
    - 'app/models/workflow_step.rb' # 15
    - 'lib/ad_roll_util.rb' # 17
    - 'lib/adwords_util.rb' # 159
    - 'lib/background_jobs.rb' # 57
    - 'lib/billing.rb' # 299
    - 'lib/bootstrap_breadcrumbs_builder.rb' # 3
    - 'lib/chart_mogul_util.rb' # 3
    - 'lib/clear_bit_util.rb' # 8
    - 'lib/contact_import.rb' # 134
    - 'lib/dictionary.rb' # 18
    - 'lib/dynamics_util/selector_store.rb' # 1
    - 'lib/eltoro_util.rb' # 14
    - 'lib/email_polling.rb' # 34
    - 'lib/email_utility.rb' # 157
    - 'lib/enquire_util.rb' # 63
    - 'lib/facebook_util.rb' # 41
    - 'lib/google_api_util.rb' # 49
    - 'lib/gotomeeting_util.rb' # 3
    - 'lib/gotowebinar_util.rb' # 27
    - 'lib/history_loader.rb' # 28
    - 'lib/linkedin_util.rb' # 33
    - 'lib/nextech_util.rb' # 99
    - 'lib/nimble_util.rb' # 20
    - 'lib/nocrm_util.rb' # 26
    - 'lib/number_port.rb' # 23
    - 'lib/office365_util.rb' # 18
    - 'lib/on_time_util.rb' # 4
    - 'lib/pdf_util.rb' # 2
    - 'lib/pinterest_util.rb' # 4
    - 'lib/pipe_drive_util.rb' # 66
    - 'lib/pipe_drive_util/custom_fields.rb' # 1
    - 'lib/pipeline_deal_util.rb' # 50
    - 'lib/pipeline_deal_util/client.rb' # 2
    - 'lib/query_generator.rb' # 111
    - 'lib/report_utility.rb' # 30
    - 'lib/salesforce_util.rb' # 17
    - 'lib/saved_scripts.rb' # 43
    - 'lib/schedule_test.rb' # 3
    - 'lib/screenshot_util.rb' # 13
    - 'lib/sendgrid_parser.rb' # 12
    - 'lib/sentry_job.rb' # 3
    - 'lib/service_minder_util.rb' # 7
    - 'lib/sherpa_crm_util.rb' # 7
    - 'lib/sherpa_crm_util/client.rb' # 5
    - 'lib/sherpa_crm_util/custom_fields.rb' # 149
    - 'lib/sidekiq_metrics.rb' # 3
    - 'lib/twilio_util.rb' # 69
    - 'lib/twitter_util.rb' # 35
    - 'lib/utility.rb' # 52
    - 'lib/voicebase_util.rb' # 19
    - 'lib/voicebase_v1_util.rb' # 18
    - 'lib/web_hook_jobs.rb' # 6
    - 'lib/wordpress_util.rb' # 17
    - 'lib/workflow_engine.rb' # 140
    - 'lib/xero_util.rb' # 38
```

How do you think should I add it to the library? And how can I improve it?

P.S. Also I'm using that script when updating the rubocop version for getting the list of new cops
