### ISSUE TITLE
Bug on TodoFormatter

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#126]
Forget to add a `:` symbol after cop name on running todo formatter. 

Should be (valid yaml)

```yaml
RSpec/ExampleLength:
  Exclude:
    - 'spec/lib/dynamics_util_spec.rb' # 1
    - 'spec/lib/email_utility_spec.rb' # 2
    - 'spec/lib/freshsales_util/contacts_scope/freshsales_contact_spec.rb' # 1
    - 'spec/lib/freshsales_util_spec.rb' # 1
    - 'spec/lib/query_generator_spec.rb' # 6
    - 'spec/lib/workflow_engine_spec.rb' # 1
```

Now 

```yml
RSpec/ExampleLength
  Exclude:
    - 'spec/lib/dynamics_util_spec.rb' # 1
    - 'spec/lib/email_utility_spec.rb' # 2
    - 'spec/lib/freshsales_util/contacts_scope/freshsales_contact_spec.rb' # 1
    - 'spec/lib/freshsales_util_spec.rb' # 1
    - 'spec/lib/query_generator_spec.rb' # 6
    - 'spec/lib/workflow_engine_spec.rb' # 1
```
